import { banc } from './commun-doc.mjs';
import fs from 'fs';
const b = await banc();
const c = b.c;
const fichier = async (txt) => { await b.clic(await b.pos(`document.querySelector('.mf-bouton')`), { att: 400 }); await b.clic(await b.pos(`[...document.querySelectorAll('.mf-item')].find(x=>x.innerText.trim().startsWith(${JSON.stringify(txt)}))`), { att: 900 }); };
const etat = () => b.ev(`(()=>{const p=document.querySelector('.pdfr-page-doc').getBoundingClientRect();const t=document.querySelector('.pt-flux p').getBoundingClientRect();const k=p.width/595;const nb=document.querySelector('.ptb-pages .tnum').innerText;return {gauche:Math.round((t.left-p.left)/k*10)/10,droite:Math.round((p.right-t.right)/k*10)/10,pages:nb,k}})()`);
await b.ev(`document.querySelector('.pdfr-scroll').scrollTop=0`); await b.dormir(400);
await b.clic(await b.bouton('Sélection'));
b.ok(!(await b.ev(`!!document.querySelector('.rg-regles')`)), 'hors édition : pas de règles');
await b.clic(await b.pos(`document.querySelector('.pt-flux p')`), { att: 500 });
b.ok(await b.ev(`!!document.querySelector('.rg-regles .rg-h') && !!document.querySelector('.rg-regles .rg-v')`), 'en édition : règles en haut et à gauche de la page');
await b.capture('apres-regles', await b.ev(`(()=>{const r=document.querySelector('.pdfr-page-doc').getBoundingClientRect();return {x:r.x-6,y:r.y-6,width:Math.min(r.width+12,700),height:260}})()`));
const e0 = await etat();
console.log('   départ', JSON.stringify(e0));
await fichier('Mise en page');
b.ok(await b.ev(`!!document.querySelector('.mep-panneau')`), 'Fichier › Mise en page : panneau ouvert');
const preset = async (nom) => { await b.clic(await b.pos(`[...document.querySelectorAll('.mep-pre')].find(x=>x.innerText.trim()===${JSON.stringify(nom)})`), { att: 1500 }); return etat(); };
const eE = await preset('Étroites');
b.ok(Math.abs(eE.gauche - 36) < 3, 'Étroites : marge gauche 12,7 mm (36 unités)', JSON.stringify(eE));
await b.capture('apres-marges-etroites', await b.ev(`(()=>{const r=document.querySelector('.pdfr-scroll').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()`));
const eL = await preset('Larges');
b.ok(Math.abs(eL.gauche - 144) < 3, 'Larges : marge gauche 50,8 mm (144 unités)', JSON.stringify(eL));
b.ok(parseInt(eL.pages.split('/')[1]) > parseInt(eE.pages.split('/')[1]), 'repagination : plus de pages avec des marges larges', `${eE.pages} → ${eL.pages}`);
await b.capture('apres-marges-larges', await b.ev(`(()=>{const r=document.querySelector('.pdfr-scroll').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()`));
const eN = await preset('Normales');
b.ok(Math.abs(eN.gauche - 56) < 2, 'Normales : marge d’avant (56 unités)', JSON.stringify(eN));
// champ : haut 30 mm
await b.ev(`(()=>{const i=[...document.querySelectorAll('.mep-cote')].find(l=>l.innerText.startsWith('Haut')).querySelector('input[type=number]');const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(i,'30');i.dispatchEvent(new Event('input',{bubbles:true}));return 1})()`);
await b.dormir(1200);
const haut = await b.ev(`(()=>{const p=document.querySelector('.pdfr-page-doc').getBoundingClientRect();const t=document.querySelector('.pt-flux h1').getBoundingClientRect();return Math.round((t.top-p.top)/(p.width/595))})()`);
b.ok(haut >= 85 && haut <= 100, 'champ « Haut » à 30 mm : le texte descend (85 unités + interligne du titre)', haut + ' unités');
await c.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }); await c.send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }); await b.dormir(400);
b.ok(!(await b.ev(`!!document.querySelector('.mep-panneau')`)), 'Échap ferme le panneau');
// poignée gauche : glisser de +60 px, mesure PENDANT le geste (en direct)
await b.clic(await b.pos(`document.querySelector('.pt-flux p')`), { att: 500 });
const pg = await b.pos(`document.querySelector('.rg-h .rg-poignee.gauche')`, false);
const avant = await etat();
await c.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: pg[0], y: pg[1] });
await c.send('Input.dispatchMouseEvent', { type: 'mousePressed', x: pg[0], y: pg[1], button: 'left', clickCount: 1 });
for (let i = 1; i <= 10; i++) { await c.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: pg[0] + i * 6, y: pg[1], button: 'left', buttons: 1 }); await b.dormir(40); }
await b.dormir(500);
const pendant = await etat();
const bulle = await b.ev(`document.querySelector('.rg-valeur')?.innerText`);
await b.capture('apres-regle-glisser', await b.ev(`(()=>{const r=document.querySelector('.pdfr-page-doc').getBoundingClientRect();return {x:r.x-6,y:r.y-6,width:Math.min(r.width+12,700),height:260}})()`));
await c.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: pg[0] + 60, y: pg[1], button: 'left', clickCount: 1 });
await b.dormir(900);
b.ok(pendant.gauche > avant.gauche + 25, 'glisser la poignée : la marge suit en direct (avant le relâchement)', `${avant.gauche} → ${pendant.gauche} unités · bulle « ${bulle} »`);
const db = await b.S(`const r=await S.getOne('notes_doc','f-doc');return r.marges`);
b.ok(db && db.gauche > 25 && db.haut === 30, 'mémorisé avec le document', JSON.stringify(db));
b.ok(await b.ev(`!!document.querySelector('.rg-regles')`), 'règles toujours là après le geste (édition conservée)');
b.ok(!b.erreurs.length, '0 erreur JS', b.erreurs.join(' | '));
fs.writeFileSync('../cap/marges-attendues.json', JSON.stringify(db));
c.fermer();
